const parksData = [
    {
        "id": 1,
        "name": "Anthony Chabot Regional Park",
        "city": "Castro Valley",
        "county": "Alameda/Contra Costa",
        "lat": 37.75,
        "lng": -122.1167,
        "acres": 3342.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/anthony-chabot-regional-park"
    },
    {
        "id": 2,
        "name": "Antioch/Oakley Regional Shoreline",
        "city": "Antioch",
        "county": "Alameda/Contra Costa",
        "lat": 38.0166,
        "lng": -121.8167,
        "acres": 5.7,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/antioch-oakley-regional-shoreline"
    },
    {
        "id": 3,
        "name": "Ardenwood Historic Farm",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.55,
        "lng": -122.0667,
        "acres": 204.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/ardenwood-historic-farm"
    },
    {
        "id": 4,
        "name": "Bay Point Regional Shoreline",
        "city": "Bay Point",
        "county": "Alameda/Contra Costa",
        "lat": 38.0333,
        "lng": -121.9333,
        "acres": 137.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/bay-point-regional-shoreline"
    },
    {
        "id": 5,
        "name": "Big Break Regional Shoreline",
        "city": "Oakley",
        "county": "Alameda/Contra Costa",
        "lat": 38.05,
        "lng": -121.7167,
        "acres": 1657.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/big-break-regional-shoreline"
    },
    {
        "id": 6,
        "name": "Bishop Ranch Open Space Regional Preserve",
        "city": "San Ramon",
        "county": "Alameda/Contra Costa",
        "lat": 37.7667,
        "lng": -122.0167,
        "acres": 983.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/bishop-ranch-open-space-regional-preserve"
    },
    {
        "id": 7,
        "name": "Black Diamond Mines Regional Preserve",
        "city": "Antioch",
        "county": "Alameda/Contra Costa",
        "lat": 37.9667,
        "lng": -121.85,
        "acres": 5677.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/black-diamond-mines-regional-preserve"
    },
    {
        "id": 8,
        "name": "Briones Regional Park",
        "city": "Lafayette",
        "county": "Alameda/Contra Costa",
        "lat": 37.9333,
        "lng": -122.1667,
        "acres": 6223.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/briones-regional-park"
    },
    {
        "id": 9,
        "name": "Brooks Island Regional Preserve",
        "city": "Richmond",
        "county": "Alameda/Contra Costa",
        "lat": 37.9167,
        "lng": -122.4,
        "acres": 378.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/brooks-island-regional-preserve"
    },
    {
        "id": 10,
        "name": "Browns Island",
        "city": "Pittsburg",
        "county": "Alameda/Contra Costa",
        "lat": 38.0333,
        "lng": -121.8833,
        "acres": 600.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/browns-island"
    },
    {
        "id": 11,
        "name": "Brushy Peak Regional Preserve",
        "city": "Livermore",
        "county": "Alameda/Contra Costa",
        "lat": 37.6667,
        "lng": -121.7333,
        "acres": 1931.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/brushy-peak-regional-preserve"
    },
    {
        "id": 12,
        "name": "Carquinez Strait Regional Shoreline",
        "city": "Martinez",
        "county": "Alameda/Contra Costa",
        "lat": 38.05,
        "lng": -122.2167,
        "acres": 1550.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/carquinez-strait-regional-shoreline"
    },
    {
        "id": 13,
        "name": "Castle Rock Regional Recreation Area",
        "city": "Walnut Creek",
        "county": "Alameda/Contra Costa",
        "lat": 37.89209763284675,
        "lng": -121.99379879814697,
        "acres": 1000,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/castle-rock-regional-recreation-area"
    },
    {
        "id": 14,
        "name": "Tilden (Charles Lee Tilden) Regional Park",
        "city": "Berkeley",
        "county": "Alameda/Contra Costa",
        "lat": 37.8833,
        "lng": -122.25,
        "acres": 1467.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/tilden"
    },
    {
        "id": 15,
        "name": "Claremont Canyon Regional Preserve",
        "city": "Berkeley",
        "county": "Alameda/Contra Costa",
        "lat": 37.85,
        "lng": -122.2167,
        "acres": 3.2,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/claremont-canyon-regional-preserve"
    },
    {
        "id": 16,
        "name": "Contra Loma Regional Park",
        "city": "Antioch",
        "county": "Alameda/Contra Costa",
        "lat": 37.9833,
        "lng": -121.7667,
        "acres": 681.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/contra-loma-regional-park"
    },
    {
        "id": 17,
        "name": "Coyote Hills Regional Park",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.55,
        "lng": -122.1,
        "acres": 1238.7,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/coyote-hills-regional-park"
    },
    {
        "id": 18,
        "name": "Crockett Hills Regional Park",
        "city": "Crockett",
        "county": "Alameda/Contra Costa",
        "lat": 38.05,
        "lng": -122.2333,
        "acres": 2114.8,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/crockett-hills"
    },
    {
        "id": 19,
        "name": "Cull Canyon Regional Recreation Area",
        "city": "Castro Valley",
        "county": "Alameda/Contra Costa",
        "lat": 37.65,
        "lng": -122.0333,
        "acres": 361.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/cull-canyon"
    },
    {
        "id": 20,
        "name": "Deer Valley Regional Park",
        "city": "Antioch",
        "county": "Alameda/Contra Costa",
        "lat": 37.9167,
        "lng": -121.8333,
        "acres": 3448.2,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/deer-valley-regional-park"
    },
    {
        "id": 21,
        "name": "Del Valle Regional Park",
        "city": "Livermore",
        "county": "Alameda/Contra Costa",
        "lat": 37.5833,
        "lng": -121.6833,
        "acres": 1284.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/del-valle"
    },
    {
        "id": 22,
        "name": "Diablo Foothills Regional Park",
        "city": "Walnut Creek",
        "county": "Alameda/Contra Costa",
        "lat": 37.8833,
        "lng": -122.0,
        "acres": 996.2,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/diablo-foothills"
    },
    {
        "id": 23,
        "name": "Don Castro Regional Recreation Area",
        "city": "Hayward",
        "county": "Alameda/Contra Costa",
        "lat": 37.6833,
        "lng": -122.0833,
        "acres": 94.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/don-castro"
    },
    {
        "id": 24,
        "name": "Redwood (Dr. Aurelia Reinhardt Redwood) Regional Park",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.8167,
        "lng": -122.1833,
        "acres": 1783.7,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/reinhardt-redwood"
    },
    {
        "id": 25,
        "name": "Dublin Hills Regional Park",
        "city": "Dublin",
        "county": "Alameda/Contra Costa",
        "lat": 37.7167,
        "lng": -121.8833,
        "acres": 642.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/dublin-hills"
    },
    {
        "id": 26,
        "name": "Dumbarton Quarry Campground on the Bay",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.5167,
        "lng": -122.1167,
        "acres": 37.1,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/dumbarton-quarry"
    },
    {
        "id": 27,
        "name": "Five Canyons Open Space",
        "city": "Castro Valley",
        "county": "Alameda/Contra Costa",
        "lat": 37.7833,
        "lng": -122.0333,
        "acres": 226.2,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/five-canyons"
    },
    {
        "id": 28,
        "name": "Garin Regional Park",
        "city": "Hayward",
        "county": "Alameda/Contra Costa",
        "lat": 37.6167,
        "lng": -122.0,
        "acres": 4449.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/garin-dry-creek"
    },
    {
        "id": 29,
        "name": "Dry Creek Pioneer Regional Park",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.6,
        "lng": -122.0167,
        "acres": 1675.1,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/garin-dry-creek"
    },
    {
        "id": 30,
        "name": "Hayward Regional Shoreline",
        "city": "Hayward",
        "county": "Alameda/Contra Costa",
        "lat": 37.6333,
        "lng": -122.1167,
        "acres": 1023.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/hayward-regional-shoreline"
    },
    {
        "id": 31,
        "name": "Huckleberry Botanic Regional Preserve",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.8167,
        "lng": -122.2,
        "acres": 238.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/huckleberry-botanic-regional-preserve"
    },
    {
        "id": 32,
        "name": "Judge John Sutter Regional Shoreline",
        "city": "Antioch",
        "county": "Alameda/Contra Costa",
        "lat": 38.0,
        "lng": -121.85,
        "acres": 32.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/judge-john-sutter-regional-shoreline"
    },
    {
        "id": 33,
        "name": "Kennedy Grove Regional Recreation Area",
        "city": "El Sobrante",
        "county": "Alameda/Contra Costa",
        "lat": 37.9667,
        "lng": -122.2833,
        "acres": 218.1,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/kennedy-grove-regional-recreation-area"
    },
    {
        "id": 34,
        "name": "Lake Chabot Regional Park",
        "city": "Castro Valley",
        "county": "Alameda/Contra Costa",
        "lat": 37.7167,
        "lng": -122.1167,
        "acres": 1628.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/lake-chabot-regional-park"
    },
    {
        "id": 35,
        "name": "Las Trampas Wilderness Regional Preserve",
        "city": "San Ramon",
        "county": "Alameda/Contra Costa",
        "lat": 37.8167,
        "lng": -122.0167,
        "acres": 5887.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/las-trampas-wilderness-regional-preserve"
    },
    {
        "id": 36,
        "name": "Leona Canyon Regional Open Space Preserve",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.75,
        "lng": -122.1833,
        "acres": 297.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/leona-canyon"
    },
    {
        "id": 37,
        "name": "Little Hills Regional Recreation Area",
        "city": "San Pablo",
        "county": "Alameda/Contra Costa",
        "lat": 37.81002212697784,
        "lng": -122.04367616409863,
        "acres": 1000,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/little-hills"
    },
    {
        "id": 38,
        "name": "Martin Luther King Jr. Regional Shoreline",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.7833,
        "lng": -122.2167,
        "acres": 773.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/martin-luther-king-jr-regional-shoreline"
    },
    {
        "id": 39,
        "name": "McLaughlin Eastshore State Park",
        "city": "Berkeley",
        "county": "Alameda/Contra Costa",
        "lat": 37.8667,
        "lng": -122.3167,
        "acres": 1896.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/mclaughlin-eastshore"
    },
    {
        "id": 40,
        "name": "Miller/Knox Regional Shoreline",
        "city": "Richmond",
        "county": "Alameda/Contra Costa",
        "lat": 37.9167,
        "lng": -122.3833,
        "acres": 317.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/miller-knox"
    },
    {
        "id": 41,
        "name": "Mission Peak Regional Preserve",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.5167,
        "lng": -121.8833,
        "acres": 3039.1,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/mission-peak-regional-preserve"
    },
    {
        "id": 42,
        "name": "Morgan Territory Regional Preserve",
        "city": "Clayton",
        "county": "Alameda/Contra Costa",
        "lat": 37.85,
        "lng": -121.8167,
        "acres": 6090.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/morgan-territory-regional-preserve"
    },
    {
        "id": 43,
        "name": "Ohlone Wilderness Regional Preserve",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.5167,
        "lng": -121.8167,
        "acres": 9047.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/ohlone-wilderness-regional-preserve"
    },
    {
        "id": 44,
        "name": "Oyster Bay Regional Shoreline",
        "city": "San Leandro",
        "county": "Alameda/Contra Costa",
        "lat": 37.6833,
        "lng": -122.2,
        "acres": 194.8,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/oyster-bay-regional-shoreline"
    },
    {
        "id": 45,
        "name": "Pleasanton Ridge Regional Park",
        "city": "Pleasanton",
        "county": "Alameda/Contra Costa",
        "lat": 37.6333,
        "lng": -121.8833,
        "acres": 8923.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/pleasanton-ridge-regional-park"
    },
    {
        "id": 46,
        "name": "Point Isabel Regional Shoreline",
        "city": "Richmond",
        "county": "Alameda/Contra Costa",
        "lat": 37.9,
        "lng": -122.3667,
        "acres": 38.0,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/point-isabel-regional-shoreline"
    },
    {
        "id": 47,
        "name": "Point Pinole Regional Shoreline",
        "city": "Richmond",
        "county": "Alameda/Contra Costa",
        "lat": 37.9833,
        "lng": -122.3667,
        "acres": 2202.8,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/point-pinole-regional-shoreline"
    },
    {
        "id": 48,
        "name": "Quarry Lakes Regional Recreation Area",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.5333,
        "lng": -121.9667,
        "acres": 479.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/quarry-lakes-regional-recreation-area"
    },
    {
        "id": 49,
        "name": "Robert W. Crown Memorial State Beach",
        "city": "Alameda",
        "county": "Alameda/Contra Costa",
        "lat": 37.7667,
        "lng": -122.2667,
        "acres": 99.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/robert-w-crown-memorial-state-beach"
    },
    {
        "id": 50,
        "name": "Roberts Regional Recreation Area",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.8333,
        "lng": -122.1833,
        "acres": 120.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/roberts-regional-recreation-area"
    },
    {
        "id": 51,
        "name": "Round Valley Regional Preserve",
        "city": "Brentwood",
        "county": "Alameda/Contra Costa",
        "lat": 37.8833,
        "lng": -121.7167,
        "acres": 2054.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/round-valley-regional-preserve"
    },
    {
        "id": 52,
        "name": "Shadow Cliffs Regional Recreation Area",
        "city": "Pleasanton",
        "county": "Alameda/Contra Costa",
        "lat": 37.65,
        "lng": -121.8667,
        "acres": 259.2,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/shadow-cliffs-regional-recreation-area"
    },
    {
        "id": 53,
        "name": "Sibley Volcanic Regional Preserve",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.85,
        "lng": -122.2,
        "acres": 927.5,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/sibley-volcanic-regional-preserve"
    },
    {
        "id": 54,
        "name": "Sobrante Ridge Regional Preserve",
        "city": "El Sobrante",
        "county": "Alameda/Contra Costa",
        "lat": 37.9833,
        "lng": -122.2667,
        "acres": 272.4,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/sobrante-ridge"
    },
    {
        "id": 55,
        "name": "Sunol Wilderness Regional Preserve",
        "city": "Sunol",
        "county": "Alameda/Contra Costa",
        "lat": 37.5167,
        "lng": -121.8333,
        "acres": 6818.9,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/sunol-wilderness-regional-preserve"
    },
    {
        "id": 56,
        "name": "Sycamore Valley Open Space Regional Preserve",
        "city": "Danville",
        "county": "Alameda/Contra Costa",
        "lat": 37.8167,
        "lng": -121.9833,
        "acres": 692.1,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/sycamore-valley-open-space-regional-preserve"
    },
    {
        "id": 57,
        "name": "Ted and Kathy Radke Martinez Regional Shoreline",
        "city": "Martinez",
        "county": "Alameda/Contra Costa",
        "lat": 38.0167,
        "lng": -122.1333,
        "acres": 333.4,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/radke-martinez"
    },
    {
        "id": 58,
        "name": "Temescal Regional Recreation Area",
        "city": "Oakland",
        "county": "Alameda/Contra Costa",
        "lat": 37.85,
        "lng": -122.2333,
        "acres": 41.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/temescal-regional-recreation-area"
    },
    {
        "id": 59,
        "name": "Thurgood Marshall Regional Park",
        "city": "Berkeley",
        "county": "Alameda/Contra Costa",
        "lat": 37.8667,
        "lng": -122.2833,
        "acres": 2545.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/thurgood-marshall-regional-park"
    },
    {
        "id": 60,
        "name": "Tilden Nature Area",
        "city": "Berkeley",
        "county": "Alameda/Contra Costa",
        "lat": 37.8833,
        "lng": -122.25,
        "acres": 709.6,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/tilden-nature-area"
    },
    {
        "id": 61,
        "name": "Tilden Regional Parks Botanic Garden",
        "city": "Berkeley",
        "county": "Alameda/Contra Costa",
        "lat": 37.89355003836973,
        "lng": -122.24329555916034,
        "acres": 1000,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/tilden/botanic-garden"
    },
    {
        "id": 62,
        "name": "Vargas Plateau Regional Park",
        "city": "Fremont",
        "county": "Alameda/Contra Costa",
        "lat": 37.5667,
        "lng": -121.9167,
        "acres": 1260.1,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/vargas-plateau-regional-park"
    },
    {
        "id": 63,
        "name": "Vasco Caves Regional Preserve",
        "city": "Brentwood",
        "county": "Alameda/Contra Costa",
        "lat": 37.8667,
        "lng": -121.7333,
        "acres": 719.8,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/vasco-caves-regional-preserve"
    },
    {
        "id": 64,
        "name": "Waterbird Regional Preserve",
        "city": "Antioch",
        "county": "Alameda/Contra Costa",
        "lat": 38.0167,
        "lng": -121.8167,
        "acres": 198.2,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/waterbird-regional-preserve"
    },
    {
        "id": 65,
        "name": "Wildcat Canyon Regional Park",
        "city": "Richmond",
        "county": "Alameda/Contra Costa",
        "lat": 37.95,
        "lng": -122.3167,
        "acres": 2722.3,
        "description": "Beautiful park in the East Bay Regional Parks system",
        "website": "https://www.ebparks.org/parks/wildcat-canyon-regional-park"
    }
];

window.parksData = parksData;